# Generated by Django 2.2.4 on 2020-01-24 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import naccsweb.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPugsPlayerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('college', models.CharField(max_length=80)),
                ('igl', models.BooleanField()),
                ('faceit_link', models.CharField(max_length=80)),
                ('esea_link', models.CharField(max_length=80)),
                ('curr_team', models.CharField(max_length=80)),
                ('lan', models.CharField(max_length=500)),
                ('other', models.TextField(blank=True, max_length=500)),
                ('application', models.FileField(storage=naccsweb.storage_backends.PrivateMediaStorage(), upload_to='powerpugs/application/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Power Pug Player Application',
                'verbose_name_plural': 'Power Pug Player Applications',
            },
        ),
    ]
