# Generated by Django 2.2.4 on 2020-01-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import naccsweb.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('powerpugs', '0002_powerpugsplayerapplication_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpugsplayerapplication',
            name='application',
            field=models.FileField(storage=naccsweb.storage_backends.PrivateMediaStorage(), upload_to='powerpugs/general/'),
        ),
        migrations.AlterField(
            model_name='powerpugsplayerapplication',
            name='curr_team',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='powerpugsplayerapplication',
            name='igl',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='powerpugsplayerapplication',
            name='lan',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='PowerPugsIGLApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('faceit_link', models.CharField(max_length=80)),
                ('esea_link', models.CharField(max_length=80)),
                ('curr_team', models.CharField(blank=True, max_length=80)),
                ('lan', models.CharField(blank=True, max_length=500)),
                ('other', models.TextField(blank=True, max_length=500)),
                ('application', models.FileField(storage=naccsweb.storage_backends.PrivateMediaStorage(), upload_to='powerpugs/igl/')),
                ('accepted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Power Pug IGL Application',
                'verbose_name_plural': 'Power Pug IGL Applications',
            },
        ),
    ]
