# Generated by Django 2.2.4 on 2020-01-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpugs', '0003_auto_20200124_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpugsplayerapplication',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
