# Generated by Django 2.2.4 on 2020-01-25 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpugs', '0006_auto_20200125_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpugsiglapplication',
            name='status',
            field=models.TextField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Denied', 'Denied')], default='Pending'),
        ),
    ]
