# Generated by Django 2.2.4 on 2020-01-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpugs', '0007_powerpugsiglapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpugsplayerapplication',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
