# Generated by Django 2.2.4 on 2020-02-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerpugs', '0010_auto_20200131_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpugsiglapplication',
            name='other',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='powerpugsplayerapplication',
            name='other',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
