# Generated by Django 2.2.4 on 2020-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_auto_20191023_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracketname', models.CharField(blank=True, max_length=50)),
                ('upper_bracket', models.TextField(blank=True, max_length=1000)),
                ('lower_bracket', models.TextField(blank=True, max_length=1000)),
                ('finals', models.TextField(blank=True, max_length=1000)),
            ],
        ),
    ]
